
---
spring:
  config:
    activate:
      on-profile: dev
db:
  driverClassname: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/db
  username: root 
  password:  root
...  
---
spring:
  config:
    activate:
      on-profile: test
db:
  driverClassname: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin@1521:xe
  username: sys
  password:  welcome
...  